### ISSUE TITLE
Add/Delete Sections and Add/Delete CollectionView Cells

### ISSUE THREAD

**Issue by nelsaow** [giulio92/GLTableCollectionView#11]
Hi Giulio!

Great Project! Do you have any writing about Add/Delete Sections and Add/Delete CollectionView Cells from user interface, can you help me please. Thanks

**Comment by giulio92** [comment]
Hello @nelsaow,

You can add and delete `UICollectionViewCell`s simply by calling UICollectionView's [`reloadData` ](https://developer.apple.com/reference/uikit/uicollectionview/1618078-reloaddata) method, be sure to update the value inside [`collectionView(_:numberOfItemsInSection:)`](https://developer.apple.com/reference/uikit/uicollectionviewdatasource/1618058-collectionview) before calling it.
So for example if you have 20 UICollectionViewCells in a UICollectionView and you want to delete one or more just update the `numberOfItemsInSection` value from 20 to whatever number and call `reloadData` on the `UICollectionView` you're pointing to.
Since GLTableCollectionView is a `UITableViewController` you could also just call the `reloadData` method on the GLTableCollectionView to reload and update all the `UICollectionView`s with a single action.
