### ISSUE TITLE
How to get "indexPath.section" in a UICollectionView? 

### ISSUE THREAD

**Issue by dkmczk** [giulio92/GLTableCollectionView#16]
Thank you for the great project!!
When I tapped a collectionView, how can I get "indexPath.section"? 
I could get indexPath.item but indexPath.section always returns "0".

`func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        print(indexPath.section)
        print(indexPath.item)
	}`

Thank you!

**Comment by giulio92** [comment]
Hello @dkmczk,

To get the `indexPath` for a given `UICollectionView` you should rely on the `UITableView` delegate instead of the `UICollectionView` one, since you would have a `UICollectionView` for each `UITableView` section, and every collection is separated from the other one. You would have a `UICollectionView` `indexPath.section` greather than "0" only in the case you would have two `UICollectionView` inside a given `UITableView` section

**Comment by dkmczk** [comment]
Thank you so much I understood! 
I will use UITableView delegate instead.
