### ISSUE TITLE
How to change UICollectionViewCells width for different section of UITableView row.

### ISSUE THREAD

**Issue by thakurkrishna1991** [giulio92/GLTableCollectionView#27]

**Comment by giulio92** [comment]
Hello @thakurkrishna1991,

Is not difficult to do so, with the provided classes you could:

1. `return` a different `CGFloat` inside `tableView(_ tableView: , heightForRowAt indexPath:)` `func` so that the `UITableViewCell`s will have a different size, the `UICollectionViewCell` will adjust accordingly
2. Do exactly the same as above but also try to differentiate the various `UICollectionView`s by simply using the `.tag` property and then decide the size of the `UICollectionViewCell`s inside `collectionView(_ collectionView: , layout collectionViewLayout: , sizeForItemAt indexPath: )`
